### PR TITLE
Remove nav using custom layout

### PR DESCRIPTION
**Pull request by roydeanjr**
Added custom layout to remove nav elements from CDS.

### CODE REVIEW

**Comment by roydeanjr** [comment]
Ryan, please review this and merge or reject. Thx.

**Comment by ryanmitchell** [comment]
Off this week and didn’t get a chance last week. Will get to it at some point.

**Comment by roydeanjr** [comment]
Latest changes reflect a Customer Display that can look like this: 
image

**Comment by ryanmitchell** [comment]
Cool. I'll merge - this is your extension really :) 

I think eventually this 'view' should be merged into Kitchen Display as an alternative layout... but lets leave that for now!

**Pull request merged**
